In [1]:
import warnings as wns
wns.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [3]:
salary_data = pd.read_csv('./data/2020salary.csv', encoding='EUC-KR')
salary_data.head()

이름    AVG    OPS   wRC+   WAR    RNG    WAA  salary
0  구자욱  0.307  0.863  126.0  3.36   3.67  0.074   36000
1  박해민  0.292  0.764   99.1  2.56  17.38  1.768   38000
2  김헌곤  0.245  0.616   64.8 -0.40   2.67  0.130   16000
3  김동엽  0.311  0.865  121.8  2.13   0.14 -0.166   21000
4  김상수  0.304  0.798  118.2  3.26  -4.22 -0.208   25000

In [4]:
salary_data.drop(['이름'], axis=1, inplace=True)
salary_data.head()

AVG    OPS   wRC+   WAR    RNG    WAA  salary
0  0.307  0.863  126.0  3.36   3.67  0.074   36000
1  0.292  0.764   99.1  2.56  17.38  1.768   38000
2  0.245  0.616   64.8 -0.40   2.67  0.130   16000
3  0.311  0.865  121.8  2.13   0.14 -0.166   21000
4  0.304  0.798  118.2  3.26  -4.22 -0.208   25000

In [5]:
data = np.array(salary_data, dtype=np.float32)
print(type(data))
data

<class 'numpy.ndarray'>


array([[ 3.07000e-01,  8.63000e-01,  1.26000e+02,  3.36000e+00,
         3.67000e+00,  7.40000e-02,  3.60000e+04],
       [ 2.92000e-01,  7.64000e-01,  9.91000e+01,  2.56000e+00,
         1.73800e+01,  1.76800e+00,  3.80000e+04],
       [ 2.45000e-01,  6.16000e-01,  6.48000e+01, -4.00000e-01,
         2.67000e+00,  1.30000e-01,  1.60000e+04],
       [ 3.11000e-01,  8.65000e-01,  1.21800e+02,  2.13000e+00,
         1.40000e-01, -1.66000e-01,  2.10000e+04],
       [ 3.04000e-01,  7.98000e-01,  1.18200e+02,  3.26000e+00,
        -4.22000e+00, -2.08000e-01,  2.50000e+04],
       [ 2.32000e-01,  6.63000e-01,  7.03000e+01,  4.20000e-01,
         7.50000e-01,  3.77000e-01,  7.00000e+03],
       [ 2.32000e-01,  5.73000e-01,  5.32000e+01,  1.20000e-01,
         1.09000e+00,  2.77000e-01,  7.00000e+03],
       [ 1.81000e-01,  6.18000e-01,  5.01000e+01, -9.20000e-01,
         2.03000e+00, -2.17000e-01,  7.00000e+03],
       [ 2.58000e-01,  6.32000e-01,  6.31000e+01, -3.50000e-01,
         3.15000

In [6]:
xData = data[:, 0:6]
print(type(xData))
print(xData)

<class 'numpy.ndarray'>
[[ 3.070e-01  8.630e-01  1.260e+02  3.360e+00  3.670e+00  7.400e-02]
 [ 2.920e-01  7.640e-01  9.910e+01  2.560e+00  1.738e+01  1.768e+00]
 [ 2.450e-01  6.160e-01  6.480e+01 -4.000e-01  2.670e+00  1.300e-01]
 [ 3.110e-01  8.650e-01  1.218e+02  2.130e+00  1.400e-01 -1.660e-01]
 [ 3.040e-01  7.980e-01  1.182e+02  3.260e+00 -4.220e+00 -2.080e-01]
 [ 2.320e-01  6.630e-01  7.030e+01  4.200e-01  7.500e-01  3.770e-01]
 [ 2.320e-01  5.730e-01  5.320e+01  1.200e-01  1.090e+00  2.770e-01]
 [ 1.810e-01  6.180e-01  5.010e+01 -9.200e-01  2.030e+00 -2.170e-01]
 [ 2.580e-01  6.320e-01  6.310e+01 -3.500e-01  3.150e+00  2.880e-01]
 [ 3.050e-01  7.290e-01  9.080e+01  5.500e-01 -3.260e+00  1.740e-01]
 [ 3.290e-01  9.570e-01  1.497e+02  4.690e+00  3.230e+00 -6.440e-01]
 [ 2.350e-01  5.910e-01  5.010e+01 -8.000e-02  4.030e+00  9.110e-01]
 [ 2.960e-01  7.250e-01  9.960e+01  1.490e+00  2.860e+00 -6.000e-03]
 [ 2.890e-01  7.920e-01  1.102e+02  3.560e+00  1.620e+00  8.060e-01]
 [ 2.390e-

In [7]:
yData = data[:, 6:] # 2차원 데이터로 뽑아낸다. => 변화 요인이 2차원이므로 결과도 2차원 형태로 뽑아내야 한다.
print(type(yData))
print(yData)

<class 'numpy.ndarray'>
[[ 36000.]
 [ 38000.]
 [ 16000.]
 [ 21000.]
 [ 25000.]
 [  7000.]
 [  7000.]
 [  7000.]
 [  5700.]
 [ 12000.]
 [ 31000.]
 [ 15500.]
 [ 13000.]
 [ 14000.]
 [  6500.]
 [  8000.]
 [  5500.]
 [  5700.]
 [  6000.]
 [112850.]
 [ 48000.]
 [ 76000.]
 [  6500.]
 [  3500.]
 [  6000.]
 [  7500.]
 [  3500.]
 [  7000.]
 [ 67710.]
 [ 10000.]
 [ 55000.]
 [ 22500.]
 [ 17000.]
 [  6000.]
 [  7000.]
 [ 11000.]
 [  5600.]
 [  3500.]
 [150000.]
 [  4300.]
 [  6000.]
 [ 13500.]
 [ 12000.]
 [ 12000.]
 [  3600.]
 [  8700.]
 [ 10000.]
 [  5400.]
 [ 17300.]
 [  4500.]
 [ 12000.]
 [ 17000.]
 [ 23000.]
 [ 63000.]
 [ 27000.]
 [  6600.]
 [ 12000.]
 [124135.]
 [  4800.]
 [ 78000.]
 [ 14000.]
 [  5500.]
 [  6300.]
 [ 21000.]
 [ 19000.]
 [ 18000.]
 [ 10000.]
 [ 30000.]
 [ 67710.]
 [  5000.]
 [  7300.]
 [ 13000.]
 [  7000.]
 [  4300.]
 [ 10500.]
 [  8500.]
 [ 10000.]
 [  4500.]
 [ 10000.]
 [ 40000.]
 [ 11000.]
 [  6000.]
 [  5300.]
 [  4200.]
 [ 12500.]
 [ 10000.]
 [  2700.]
 [  4500.]
 [ 56425

In [8]:
X = tf.placeholder(dtype=tf.float32, shape=[None, 6]) 
Y = tf.placeholder(dtype=tf.float32, shape=[None, 1])

In [9]:
a = tf.Variable(tf.random_uniform([6, 1]), dtype=tf.float32)
b = tf.Variable(tf.random_uniform([1]), dtype=tf.float32)

In [10]:
y = tf.matmul(X, a) + b
loss = tf.reduce_mean(tf.square(y - Y))
gradient_descent = tf.train.GradientDescentOptimizer(0.00000005).minimize(loss)

In [11]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for i in range(1000001):
    loss_, y_, _ = sess.run([loss, y, gradient_descent], feed_dict={X: xData, Y: yData})
    if i % 5000 == 0:
        print('Epoch: {0:6d}, loss: {1:12.3f}, price: {2:8.2f}'.format(i, loss_, y_[0][0]))

saver = tf.train.Saver()
save_path = saver.save(sess, './data/saved.cpkt')
print('학습된 모델을 저장했습니다.')

Epoch:      0, loss: 1003120896.000, price:    63.76
Epoch:   5000, loss: 521174112.000, price: 28362.21
Epoch:  10000, loss: 520775968.000, price: 28643.67
Epoch:  15000, loss: 520419296.000, price: 28670.50
Epoch:  20000, loss: 520064448.000, price: 28695.46
Epoch:  25000, loss: 519711744.000, price: 28720.28
Epoch:  30000, loss: 519360672.000, price: 28744.98
Epoch:  35000, loss: 519011488.000, price: 28769.55
Epoch:  40000, loss: 518664096.000, price: 28794.01
Epoch:  45000, loss: 518318336.000, price: 28818.35
Epoch:  50000, loss: 517973920.000, price: 28842.58
Epoch:  55000, loss: 517632384.000, price: 28866.65
Epoch:  60000, loss: 517292192.000, price: 28890.61
Epoch:  65000, loss: 516953472.000, price: 28914.47
Epoch:  70000, loss: 516616096.000, price: 28938.21
Epoch:  75000, loss: 516280608.000, price: 28961.84
Epoch:  80000, loss: 515946112.000, price: 28985.37
Epoch:  85000, loss: 515612928.000, price: 29008.81
Epoch:  90000, loss: 515283264.000, price: 29032.06
Epoch:  950

Epoch: 790000, loss: 478989504.000, price: 31472.78
Epoch: 795000, loss: 478771808.000, price: 31486.21
Epoch: 800000, loss: 478554304.000, price: 31499.63
Epoch: 805000, loss: 478337152.000, price: 31513.06
Epoch: 810000, loss: 478120192.000, price: 31526.49
Epoch: 815000, loss: 477903424.000, price: 31539.92
Epoch: 820000, loss: 477686880.000, price: 31553.34
Epoch: 825000, loss: 477470528.000, price: 31566.77
Epoch: 830000, loss: 477254496.000, price: 31580.19
Epoch: 835000, loss: 477038624.000, price: 31593.62
Epoch: 840000, loss: 476823008.000, price: 31607.04
Epoch: 845000, loss: 476608224.000, price: 31620.04
Epoch: 850000, loss: 476393632.000, price: 31633.00
Epoch: 855000, loss: 476179328.000, price: 31645.96
Epoch: 860000, loss: 475965248.000, price: 31658.92
Epoch: 865000, loss: 475751392.000, price: 31671.88
Epoch: 870000, loss: 475537696.000, price: 31684.84
Epoch: 875000, loss: 475324224.000, price: 31697.81
Epoch: 880000, loss: 475110976.000, price: 31710.77
Epoch: 88500